title: "Vid Luther's dotfiles"
email: vid@luther.io
description: >- # this means to ignore newlines until "baseurl:"
  A site for me to store my dotfiles and other tips and tricks I need
  to work on a daily basis. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dotfiles.luther.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vidluther
github_username:  vidluther

theme: just-the-docs

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

color_scheme: dark
